"api":
  - changed-files:
    - any-glob-to-any-file: apps/api/**/*

"discord-bot":
  - changed-files:
    - any-glob-to-any-file: apps/discord-bot/**/*

"scripts":
  - changed-files:
    - any-glob-to-any-file: apps/scripts/**/*

"site":
  - changed-files:
    - any-glob-to-any-file: apps/site/**/*

"support-bot":
  - changed-files:
    - any-glob-to-any-file: apps/support-bot/**/*

"verify-server":
  - changed-files:
    - any-glob-to-any-file: apps/verify-server/**/*

"@statsify/api-client":
  - changed-files:
    - any-glob-to-any-file: packages/api-client/**/*

"@statsify/assets":
  - changed-files:
    - any-glob-to-any-file: packages/assets/**/*

"@statsify/discord":
  - changed-files:
    - any-glob-to-any-file: packages/discord/**/*

"@statsify/logger":
  - changed-files:
    - any-glob-to-any-file: packages/logger/**/*

"@statsify/math":
  - changed-files:
    - any-glob-to-any-file: packages/math/**/*

"@statsify/rendering":
  - changed-files:
    - any-glob-to-any-file: packages/rendering/**/*

"@statsify/schemas":
  - changed-files:
    - any-glob-to-any-file: packages/schemas/**/*

"@statsify/skin-renderer":
  - changed-files:
    - any-glob-to-any-file: packages/skin-renderer/**/*

"@statsify/util":
  - changed-files:
    - any-glob-to-any-file: packages/util/**/*
